#!/usr/bin/env bash

## VARIABLES
HERE=$(dirname $0)
HOSTNAME=$(hostname)
OS_NAME=$(uname -s)
OS_RELEASE=$(uname -r)
OS=${OS_NAME// /_}

BUILD_STYLE=${1:-debug}

# CONFIGURATION

shopt -s nullglob
src_files=(src/*.cpp runtime/*.cpp)
shopt -u nullglob

BUILD_TIMEBOX=5

## TOOLS
ASTYLE=astyle
GIT=git


BUILD_DIR=${HERE}/builds/${HOSTNAME}

## IMPLEMENTATION

function require_dir() {
    mkdir -p "${BUILD_DIR}"
}

function rebuild_dir() {
    [[ -d "${BUILD_DIR}" ]] && rm -rf "${BUILD_DIR}"
    require_dir
}

function code_format() {
    astyle_output=$(
        ${ASTYLE} -n -Q --options=${HERE}/.astylerc \
            -r "src/*.*" -r "include/*.*" -r "runtime/*.*" |
            grep '^Formatted'
    )
    if [[ -n "${astyle_output}" ]]; then
        printf "astyle returned '%s', please commit these modifications\n" "${astyle_output}"
        exit 1
    fi
}

function check_clean() {
    git_output=$(${GIT} clean -n | grep '^Would remove')
    if [[ -n "${git_output}" ]]; then
        printf "WARNING some files were produced by the build outside of %s:\n%s\n" "${BUILD_DIR}" "${git_output}"
    fi
}

function compile_default() {
    printf "define a compilation function for your OS ${OS} or host ${HOSTNAME}!\n"
    exit 1
}

function compile_gxxlike() {
    CFLAGS="$CFLAGS -isystem ${HERE}/include"
    CFLAGS="$CFLAGS -Wall -Wextra -Werror"
    CFLAGS="$CFLAGS -Wno-padded -Wno-unused-parameter -Wno-conversion"

    if [[ -n "${VERBOSE}" ]]; then
        CFLAGS="$CFLAGS -v"
    fi

    if [[ "debug" == "${BUILD_STYLE}" ]]; then
        CFLAGS="$CFLAGS -g"
    fi

    "${CXX}" -std=c++11 ${CFLAGS} ${src_files[*]} -o ${BUILD_DIR}/main
}

function compile_clang() {
    CFLAGS="$CFLAGS -stdlib=libc++"
    CXX=clang++
    compile_gxxlike
}

function compile_Darwin() {
    src_files=(${src_files[@]} runtime/Darwin/*.cpp)
    CFLAGS="-Wno-deprecated-declarations -framework GLUT -framework OpenGL"
    compile_clang
}

function reg_query() {
    path=$1
    value_name=$2
    reg query "$path" //v "$value_name" 2> /dev/null | awk -F'    ' '/'"${value_name}"'/ {print $4}'
}

function posix_path() {
    windows_path="$1"
    echo $(cd "$windows_path" ; pwd -P)
}

function windows_path() {
    posix_path="$1"
    echo $(cd "$posix_path" ; pwd -W) | sed -e 's,\/,\\,g'
}

function set_vcenv() {
    VS_WINDIR=$1

    (cmd <<EOF
bash -c set > "${BUILD_DIR}"/vcvarsall-prev.env
"${VS_WINDIR}/vcvarsall.bat"
bash -c set > "${BUILD_DIR}"/vcvarsall-after.env
EOF
    ) > /dev/null

    diff -u "${BUILD_DIR}"/vcvarsall-prev.env "${BUILD_DIR}"/vcvarsall-after.env | grep -e '^\+[^\+]' | cut -c 2- | grep -v -e '^\!' > "${BUILD_DIR}/vc.env"

    . ${BUILD_DIR}/vc.env
}

function compile_vstudio() {
    vstudio_ver=$1
    VS_WINDIR=$(reg_query "HKLM\\SOFTWARE\\Microsoft\\VisualStudio\\SxS\\VC7" "$vstudio_ver")
    if [[ -z $VS_WINDIR ]]; then
        printf 'ERROR cannot find visual studio version: %s\n' "$vstudio_ver"
        exit 1
    fi


    set_vcenv "${VS_WINDIR}"

    CL_CMD="cl.exe"
    LIB_CMD="lib.exe"
    LINK_CMD="link.exe"

    CLFLAGS="//W3 //WX- //Zc:forScope"
    LINK_FLAGSS="$LINK_FLAGS"

    BUILD_WINDIR="$(windows_path "${BUILD_DIR}/")"
    MAIN_EXE="$BUILD_WINDIR"\\main.exe
    export LIB
    export INCLUDE

    for srcf in "${src_files[@]}"; do
        "${CL_CMD}" $CLFLAGS "$srcf" //c //nologo //Iinclude //Fo${BUILD_WINDIR}\\
        if [[ $? -ne 0 ]]; then
          printf 'ERROR compiling %s\n' "$srcf"
          exit 1
        fi
    done

    "${LINK_CMD}" ${LINK_FLAGS} //OUT:${MAIN_EXE} ${BUILD_DIR}/*.obj
    return
}

# windows 7 on msys with vstudio express 2013
function compile_MINGW32_NT-6.1() {
    src_files=(${src_files[@]} runtime/NT/*.cpp)
    LINK_FLAGS="opengl32.lib"
    compile_vstudio "12.0"
}

# windows 8 on msys with vstudio express 2013
function compile_MINGW32_NT-6.2() {
    src_files=(${src_files[@]} runtime/NT/*.cpp)
    LINK_FLAGS="opengl32.lib"
    compile_vstudio "12.0"
}

function compile() {
    if [[ -z "$src_files" ]]; then
        printf "ERROR no source files? %s\n" "${src_files}"
    fi

    for f in ${src_files[@]}; do
        if [[ ! -e ${f} ]] ; then
            printf "ERROR could not find source file %s in %s\n" "${f}" "${src_files}"
            exit 1
        fi
    done

    if [[ "function" = $(type -t "compile_${HOSTNAME}") ]]; then
        compile_${HOSTNAME}
        return
    fi

    if [[ "function" = $(type -t "compile_${OS}") ]]; then
        compile_${OS}
        return
    fi

    compile_default
}

function timed_compile() {
    ts_start=$(date +'%s')
    compile
    RC=$?
    ts_end=$(date +'%s')
    ts_elapsed=$(($ts_end - $ts_start))

    cat=INFO
    if [[ ts_elapsed -gt ${BUILD_TIMEBOX} ]]; then
        cat="ERROR"
    fi
    printf '%s compilation took %d seconds\n' $cat $ts_elapsed
    return $RC
}

function show_todo() {
    grep -e 'TODO:' "${src_files[@]}" | while read match ; do
        printf "WARNING %s\n" "$match"
    done
}

printf "INFO building on %s (os: %s, build style: %s)\n" "${HOSTNAME}" "${OS}" "${BUILD_STYLE}"
rebuild_dir && timed_compile && code_format && show_todo && check_clean

if [[ $? -ne 0 ]]; then
    printf "ERROR error\n"
    exit 1
fi

printf "INFO success\n"
printf "INFO results:\n"
find ${BUILD_DIR} -type f
